version: "3.9"

services:
  web:
    build: .
    expose:
      - "8000"
    depends_on:
      - localstack
    networks:
      - app_network

  localstack:
    image: localstack/localstack
    container_name: my_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - AWS_ACCESS_KEY_ID=access_key_id
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=secret
    networks:
      - app_network

  load_balancer:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
