version: "3.9"

services:
  web:
    build: .
    expose:
      - "8000"
    labels:
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.services.web.loadbalancer.server.port=8000"
    depends_on:
      - localstack
    networks:
      - app_network

  localstack:
    image: localstack/localstack
    container_name: my_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - AWS_ACCESS_KEY_ID=access_key_id
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=secret
    networks:
      - app_network

  traefik:
    image: traefik:v2.10
    ports:
      - "8000:80"
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
