version: "3.8"
services:
  dynamodb:
    image: localstack/localstack
    container_name: localstack-dynamodb
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack-data:/var/lib/localstack"
